### ISSUE TITLE
Action doesn't handle PRs bigger than 30 files (default page size)

### ISSUE THREAD

**Issue by marcin-ptaszynski** [Decathlon/pull-request-labeler-action#16]
Labels are only applied based on to first page of listed files under PR. See: https://developer.github.com/v3/#pagination

**Comment by rdelgatte** [comment]
Hello @marcin-ptaszynski, thank you for reporting this issue. 

I reworked that in #18 so you can take a look and test by updating your `main.workflow` file changing the `uses` value as following:
```
action "PR label by Files" {
  uses = "decathlon/pull-request-labeler-action@feat/handleAllFiles"
  secrets = ["GITHUB_TOKEN"]
}
```
Please give me any feedback once you had a chance testing it. 
Thank you in advance!

**Comment by marcin-ptaszynski** [comment]
Hi @rdelgatte. I've confirmed that your fix works as expected.

Thanks a lot!

**Comment by rdelgatte** [comment]
That's cool, thank you for your feedback, it will be merged soon hopefully ;-)

**Comment by lusoalex** [comment]
@marcin-ptaszynski We are currently building the docker image tag 1.1.1 so you may use with
uses = "decathlon/pull-request-labeler-action@v1.1.1" to enhance speed on your action.

Thanks a lot for your report!

**Comment by lusoalex** [comment]
> That's neat, thanks!

You are welcome, FYI, we built a v2.0.0 compliant with YAML syntax introduced by the new beta.
Please have a look at: 
https://github.com/Decathlon/pull-request-labeler-action/blob/master/README.md#settings-for-v200-release
Thanks.
