### ISSUE TITLE
Support automatic review requests

### ISSUE THREAD

**Issue by rogerzxu** [Decathlon/pull-request-labeler-action#28]
In the same way that labels are automatically attached, would it be possible to also automatically request reviewers as well based on file regex? 

The use case is pretty similar as with labels, but it would be extra helpful to be able to tag the specific domain expert, like

`*.sql` -> request review from DBA
`*.js` -> request review from front-end guy

etc.

**Comment by rdelgatte** [comment]
It is actually a good idea but I think it should be done in another custom github action as it has a different concern. 
I don't know if such action already exists in the market place but I guess it shouldn't be too hard to do.

It may require to get user roles / domains and get a configurable mapping with labels but the mechanics should probable be the same as the labeler action.

**Comment by beaussart** [comment]
If I am correct, this can be handled with the [CODEOWNER](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) and settings review from codeowner :)

**Comment by rdelgatte** [comment]
I did not know this feature but I guess it should do the trick 👍It looks cool, thank you for sharing @beaussart

**Comment by rogerzxu** [comment]
Thanks @beaussart, did not know about this either, but it works perfectly!
