### ISSUE TITLE
HttpError: Resource not accessible by integration 

### ISSUE THREAD

**Issue by Kreyren** [Decathlon/pull-request-labeler-action#34]
Why is this failing? Can you exclude pebcak on my end?

```
ℹ  info      Open sourced by
...
ℹ  info      Running Action
ℹ  info       Configured filters:  [ { regExp: '.*\\.rs+$', labels: [ 'rustlang' ] },
  { regExp: '.*\\.py+$', labels: [ 'python' ] },
  { regExp: '.*\\.c+$', labels: [ 'c-lang' ] },
  { regExp: '.*\\.cpp+$', labels: [ 'CPP' ] },
  { regExp: '.*\\.sh+$', labels: [ 'shell' ] },
  { regExp: '.*\\.bash+$', labels: [ 'bash' ] },
  { regExp: '.*\\.br+$', labels: [ 'brainfuck' ] },
  { regExp: '^(.*\\Cargo.toml)$', labels: [ 'dependencies' ] } ]
ℹ  info      Checking files list for PR#37
ℹ  info      Listing files (page: 1 | per_page: 100)...
ℹ  info      Loaded 2 files
ℹ  info      Checking files... [ 'ping', 'src/bin/main.py' ]
ℹ  info      Labels to remove:  []
ℹ  info      Labels to add:  [ 'python' ]
✖  fatal     HttpError: Resource not accessible by integration 
    at response.text.then.message (/app/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
##[error]Docker run failed with exit code 1
```

Affected run: https://github.com/RXT0112/Zernit/pull/37/checks?check_run_id=427509002

**Comment by rdelgatte** [comment]
Hi @Kreyren, thank you for sharing. I've seen this in the past but it appeared more like an availability of Github API when trying to attach labels to the pull request. 
Could you please try running again the labeler and keep me posted? It may require a retry mechanism if this happens too often.

Thank you

**Comment by Kreyren** [comment]
@rdelgatte triggered the test again and the issue still persist https://github.com/RXT0112/Zernit/runs/427574403?check_suite_focus=true

Reproducable always

quick disclaimer: This is first time that i'm using this action and i've set it up using default configuration and adapted config file.

**Comment by Kreyren** [comment]
Works now ^^

**Comment by rdelgatte** [comment]
Thank you for your feedback, I'll keep trying to stabilize the action with the new version of octokit
