### ISSUE TITLE
Excluding path

### ISSUE THREAD

**Issue by Kitzunu** [Decathlon/pull-request-labeler-action#40]
Hi :)

This is a great tool that I want to use in an Open Source environment.
My only issue is that I cannot figure out how to exclude a path from getting a label... Is this possible?

Kind regards,

**Comment by rdelgatte** [comment]
Hello @Kitzunu thank you for your feedback!
This isn't possible (so far) unfortunately but I guess you could use more specific regular expressions no to look into your excluded paths if you really need to. 
Feel free to share any examples if you have some in mind.

**Comment by Kitzunu** [comment]
Yea I tried with the regular exlude paths that you can do with Regular expressions but nothing worked, thanks for the feedback

**Comment by Kitzunu** [comment]
Dont know if you want me to open a new thread...
But after merging the action, I get this fatal error on PRs

```
✖  fatal     HttpError: Resource not accessible by integration 
    at response.text.then.message (/app/node_modules/@octokit/request/dist-node/index.js:66:23)
```
Any clue?

**Comment by rdelgatte** [comment]
I've seen this error happening from time to time. It looks like this may be linked to a Github API unavailability when trying to run the PR update (to attach labels to it). I couldn't be able to reproduce more often so I could fix it properly. Does this happen everytime on your side? Have you tried to replay the action afterwards?

**Comment by Kitzunu** [comment]
Yea, it is happening on every mew PR and every re-run.

The weird part is that it did not fail on the initial PR to implement this 🤷
